# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '0 22 * * *'  ## UTC+8 6:00 UTC+8
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      # Installing dependencies
      - name: Install moudles
        run: npm install

      # Setup environment variables and check in
      - name: Check in
        env: 
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          EVER_PHOTO_MOBILE: ${{ secrets.EVER_PHOTO_MOBILE }}
          EVER_PHOTO_PASSWORD: ${{ secrets.EVER_PHOTO_PASSWORD }}
        run: node check_in.js
